### ISSUE TITLE
老哥, 你现在咋样了

### ISSUE THREAD

**Issue by sean-wade** [sroxck/sims-jzb#1]
你的是交感型颈椎病吗

**Comment by sroxck** [comment]
我是神经根型的,十一期间做手术了,已经好了差不多了,做的硬膜穿刺封闭,从颈7和胸1的缝隙中穿刺到颈椎硬膜神经层注射药物, 住院3天 花费4000多

**Comment by sroxck** [comment]
> 我是神经根型的,十一期间做手术了,已经好了差不多了,做的硬膜穿刺封闭,从颈7和胸1的缝隙中穿刺到颈椎硬膜神经层注射药物, 住院3天 花费4000多

**Comment by sroxck** [comment]
> 你的是交感型颈椎病吗

我是神经根型的,十一期间做手术了,已经好了差不多了,做的硬膜穿刺封闭,从颈7和胸1的缝隙中穿刺到颈椎硬膜神经层注射药物, 住院3天 花费4000多

**Comment by sean-wade** [comment]
> > 你的是交感型颈椎病吗
> 
> 我是神经根型的,十一期间做手术了,已经好了差不多了,做的硬膜穿刺封闭,从颈7和胸1的缝隙中穿刺到颈椎硬膜神经层注射药物, 住院3天 花费4000多

好吧，祝你早日康复吧~
